seed: 42
data_path: datasets/
output_path: output/
repo_name: TaroSin/HRmony
config_path: config/
catboost_params:
  iterations: 483
  depth: 8
  learning_rate: 0.0573637902482447
  loss_function: RMSE
  l2_leaf_reg: 0.3592000264374363
  eval_metric: RMSE
  od_type: Iter
  od_wait: 50
  task_type: GPU
xgboost_params:
  n_estimators: 737
  max_depth: 6
  learning_rate: 0.12589133076014447
  eval_metric: rmse
  device: cuda
  tree_method: hist
  subsample: 0.5491600210980101
  colsample_bytree: 0.590668632226121
  reg_lambda: 4.809585178239605
lr_params:
  penalty: l2
  C: 1.0
  solver: lbfgs
  max_iter: 1000
data_params:
  train_ratio: 0.8
  target_column: matching_score
  numerical_features:
  - project_duration
  - project_budget
  - project_priority
  - freelancer_experience
  - freelancer_price
