# Data Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

load_col: # 데이터셋에서 필요한 컬럼 정의
    inter: [user_id, item_id, rating]

local_col: # 모델이 실제로 학습할 때 사용하는 특정 컬럼
    inter: [user_id, item_id, rating]
    # user: [user_id, project_content, duration, budget, priority, company_id, category_id, project_skill]
    # item: [item_id, work_exp, price, category_id, freelancer_skill]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

# Model settings
model: EASE
dataset: EASE