# Data Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, timestamp]
    # item: ["item_id", "year", "genre", "writer", "director"]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
val_interval:
    timestamp: "[97830000, inf)"

# Model settings
model: EASE
dataset: EASE